=== giellalt/dict-sme-nob/dtd/smenob.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( sme ) #IMPLIED
>
<!ATTLIST r
      id ( smenob ) #IMPLIED >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>

<!ELEMENT e (lg, mg+, ig* ) >
<!ATTLIST e
      src ( nj | sk | SvSt | gt_fad | gt | fad | other | sgg | SK |
            PS_SA | KAL | nou94 | PS | husbykuhmunen | lmm | sammallahti |
            BergslandMagga | Lagercrantz | nsr | utsi | aj )  #IMPLIED
>

<!ELEMENT lg (l+, lemma_ref*, lsub*, lc*, analysis*, mini_paradigm*, algu*, orig*) >
<!ELEMENT lemma_ref (#PCDATA) > <!-- navigating in static articles -->
<!ATTLIST lemma_ref lemmaID CDATA #IMPLIED >
<!ATTLIST lg freq CDATA #IMPLIED >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT orig (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >
<!ELEMENT l (#PCDATA) >
<!ATTLIST l
      ader CDATA #IMPLIED
      pos ( A | N | V | Adv | Po | Pr | Pron | Rel |  Det | Interj | Pcle |
            Num | CC | CS | Phrase | fp-cmp ) #REQUIRED
      attr ( no ) #IMPLIED
      id CDATA #IMPLIED
      nr ( Sg | Du | Pl ) #IMPLIED
      context CDATA #IMPLIED
      type ( Rel | Pers | Indef | Refl | Dem | G3 | G7 | NomAg | Ord
      | Prop | Recipr | Coll | Interr |ACR | ABBR ) #IMPLIED
      pg ( yes | no ) #IMPLIED
      vmax ( 2 | 3 | 4) #IMPLIED
      dial ( east | west | torne | varanger ) #IMPLIED
      par CDATA #IMPLIED
      dera CDATA #IMPLIED

>
<!ATTLIST l sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED >
<!ATTLIST l paradigme ( cases ) #IMPLIED >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l src CDATA #IMPLIED >
<!ATTLIST l value CDATA #IMPLIED >


<!-- lsub = frequent subform of lemma -->
<!ELEMENT lsub (#PCDATA) >
<!ATTLIST lsub src CDATA #IMPLIED >
<!ATTLIST lsub x ( fad ) #IMPLIED >

<!-- algu = lemma IDs in the algu database -->
<!ELEMENT algu EMPTY >
<!ATTLIST algu
      lekseemi_id CDATA #REQUIRED >
<!ATTLIST algu
      sanue_id CDATA #REQUIRED >

<!ELEMENT mg (l_ref?, dg?, sg?, antg?, tg+ ) >
<!ATTLIST mg id CDATA #IMPLIED >
<!ATTLIST mg src CDATA #IMPLIED >
<!ATTLIST mg c CDATA #IMPLIED > <!-- comment -->
<!ATTLIST mg x ( fad ) #IMPLIED >
<!ATTLIST mg sem ( metaphor ) #IMPLIED > <!-- med, bot, zool, ? -->

<!-- definition  -->
<!ELEMENT dg ( re?, d, dt? ) >
<!ELEMENT d (#PCDATA) >
<!ELEMENT dt (#PCDATA) >


<!-- synonym, antonym --> 
<!ELEMENT sg ( s+ ) >
<!ELEMENT s (#PCDATA) >
<!ELEMENT antg ( ant+ ) >
<!ELEMENT ant (#PCDATA) >

<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ATTLIST i src CDATA #IMPLIED >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >



<!ELEMENT tg (re?,  ( ((t, l_ref?, morph_expl?) ))+, xg* ) >
<!ATTLIST tg
      xml:lang ( nob | eng | fra | fin ) #REQUIRED
      check CDATA #IMPLIED
>
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ATTLIST re x ( fad ) #IMPLIED >

<!ELEMENT t (#PCDATA) >
<!ATTLIST t t_type ( expl | grammarexpl | phrase ) #IMPLIED  >
<!ATTLIST t nr ( Sg | Pl ) #IMPLIED  >
<!ATTLIST t pos ( A | N | V | Adv | Po | Pr | Pron | Rel |  Det | Interj | Pcle | Num | CC | CS | fp-cmp ) #IMPLIED  >
<!ATTLIST t reg CDATA #IMPLIED >
<!ATTLIST t country CDATA #IMPLIED >

<!ATTLIST t type ( Prop | Indef | Recipr | Pers | Refl | Dem | Poss | Rel | Interr ) #IMPLIED >
<!ATTLIST t dial ( east | west | torne | varanger ) #IMPLIED >
<!ATTLIST t src CDATA #IMPLIED >
<!ATTLIST t alt_str CDATA #IMPLIED >
<!ATTLIST t sem_type ( Obj | Plc | Org | Mal ) #IMPLIED >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t href CDATA #IMPLIED >
<!ATTLIST t x ( fad ) #IMPLIED >


<!ELEMENT l_ref (#PCDATA) > <!-- reference, se også = information about words relevant to the lemma -->

<!ELEMENT morph_expl (#PCDATA) >


<!ELEMENT xg ((x, xt+)+)>
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x (#PCDATA)>
<!ATTLIST x src CDATA #IMPLIED >
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt src CDATA #IMPLIED >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >



<!--
This document is not quite finished yet...

Here are the pos tags:
 a  = Adjective
 m  = Masculine (nob)
 f  = Feminine (nob)
 n  = Neuter (nob), noun (sme)
 S  = noun, still not given gender (nob)
 v  = verb
 adv  = adverb
 num = numeral
 pcle = particle
 p  = preposition (nob)
 pr = preposition (sme)
 po = postposition (sme)
 pron  = pronoun
 i  = interjection
 cc  = conjunction
 cs  = subjunction
 im = infinitive mark å (nob)
 s  = sentence, or explanation
 x  = still no pos

Documenting
(the tags are short due to a manual cleanup)
r  root
e  entry
l  lemma
lc lemma comment
m  meaning
re restriction (semantic restriction of the following t)
t  translation
x  example
xt example translation
.g group
-->

=== giellalt/dict-sme-nob/ShortSrc/shortDict_adv_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e src="nj">
      <lg>
         <l pos="adv">eret</l>
      </lg>
      <mg>
         <tg>
            <t pos="adv">bort</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="adv">albma</l>
      </lg>
      <mg>
         <tg>
            <t pos="adv">ordentlig</t>
            <t pos="adv">skikkelig</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="adv">sahtedohko</l>
      </lg>
      <mg>
         <tg>
            <t pos="adv">tilfeldig</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="adv">uforsiktig</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-nob/ShortSrc/shortDict_nounCommon_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e>
      <lg>
         <l pos="n">vuoigatvuođalávdegoddi</l>
      </lg>
      <mg>
         <tg>
            <t nr="sg" pos="n">rettighetsutvalg</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="n">giellaráđđi</l>
      </lg>
      <mg>
         <tg>
            <t pos="n">språkråd</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="n">sámediggejoavku</l>
      </lg>
      <mg>
         <tg>
            <t pos="f">sametingsgruppe</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="n">audio-visuála</l>
      </lg>
      <mg>
         <tg>
            <t pos="a">audio-visual</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="n">A-vitamiidna</l>
      </lg>
      <mg>
         <tg>
            <t pos="n">A-vitamin</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-nob/src/A_buorre_smenob.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smenob.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smenob" xml:lang="sme">
  <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
    <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
    <ref>Work by Nils Jernsletten, Giellatekno and Divvun at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
    <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
  </lics>
  <e>
    <lg>
      <l context="buorre" pos="A">buorre</l>
      <analysis>A_Sg_Nom</analysis>
      <mini_paradigm>
        <analysis ms="A_Sg_Nom">
          <wordform>buorre (girji)</wordform>
        </analysis>
        <analysis ms="A_Sg_Acc">
          <wordform>buori (girjji)</wordform>
        </analysis>
        <analysis ms="A_Sg_Ill">
          <wordform>buori (girj√°i)</wordform>
        </analysis>
        <analysis ms="A_Sg_Loc">
          <wordform>buori (girjjis)</wordform>
        </analysis>
        <analysis ms="A_Sg_Com">
          <wordform>buriin (girjjiin)</wordform>
        </analysis>
        <analysis ms="A_Pl_Nom">
          <wordform>buorit (girjjit)</wordform>
          <wordform>(girjjit leat) buorit</wordform>
        </analysis>
        <analysis ms="A_Pl_Acc">
          <wordform>buriid (girjjiid)</wordform>
        </analysis>
        <analysis ms="A_Pl_Ill">
          <wordform>buriid/buriide (girjjiide)</wordform>
        </analysis>
        <analysis ms="A_Pl_Loc">
          <wordform>buriin (girjjiin)</wordform>
        </analysis>
        <analysis ms="A_Ess">
          <wordform>buorren (girjin)</wordform>
        </analysis>
        <analysis ms="A_Der/Comp_A_Sg_Nom">
          <wordform>buoret</wordform>
        </analysis>
        <analysis ms="A_Der/Superl_A_Sg_Nom">
          <wordform>buoremus</wordform>
        </analysis>
      </mini_paradigm>
    </lg>
    <mg>
     <l_ref>bures_adv</l_ref>
      <tg xml:lang="nob">
        <t pos="A">god</t>
        <t pos="A">bra</t>
        <xg>
          <x>Diet girji lea buorre.</x>
          <xt>Den der bok er god.</xt>
        </xg>
        <xg>
          <x>Buorre beaivi!</x>
          <xt>God dag!</xt>
        </xg>
      </tg>
    </mg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Phrase">glad i</t>
        <xg>
          <x>Mun ledjen buorre sutnje.</x>
          <xt>Jeg var glad i henne.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <xhtml:script xmlns:xhtml="http://www.w3.org/1999/xhtml" src="../../giella-core/dicts/scripts/gt_dictionary.js" type="text/javascript"/>
</r>

=== giellalt/dict-sme-nob/src/leat_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v" context="mun">leat</l>
	 <analysis>IV_Inf</analysis>
         <analysis>IV_Ind_Prs_Inf</analysis>
         <mini_paradigm>
            <analysis ms="IV_Ind_Prs_Sg1">
               <wordform>lean</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Sg2">
               <wordform>leat</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Sg3">
               <wordform>lea</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Du1">
               <wordform>letne</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Du2">
               <wordform>leahppi</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Du3">
               <wordform>leaba</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Pl1">
               <wordform>leat</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Pl2">
               <wordform>lehpet</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prs_Pl3">
               <wordform>leat</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Sg1">
               <wordform>ledjen</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Sg2">
               <wordform>ledjet</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Sg3">
               <wordform>leai</wordform>
               <wordform>lei</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Du1">
               <wordform>leimme</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Du2">
               <wordform>leidde</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Du3">
               <wordform>leigga</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Pl1">
               <wordform>leimmet</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Pl2">
               <wordform>leiddet</wordform>
            </analysis>
            <analysis ms="IV_Ind_Prt_Pl3">
               <wordform>ledje</wordform>
            </analysis>
         </mini_paradigm>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">lean</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Sg1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leat</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Sg2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">lea</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Sg3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">letne</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Du1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leahppi</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Du2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leaba</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Du3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leat</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Pl1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">lehpet</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Pl2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leat</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prs_Pl3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">er</t>
            <t pos="v">har</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">ledjen</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Sg1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">ledjet</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Sg2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">lei</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Sg3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leai</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Sg3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leimme</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Du1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leidde</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Du2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leigga</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Du3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leimmet</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Pl1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">leiddet</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Pl2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v">ledje</l>
         <lemma_ref>leat</lemma_ref>
         <analysis>IV_Ind_Prt_Pl3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="v">var</t>
            <t pos="v">hadde</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-nob/ShortSrc/shortDict_num_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e src="nj">
      <lg>
         <l pos="num">guokte</l>
         <lc>guovtti</lc>
      </lg>
      <mg>
         <tg>
            <t pos="num">to</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="num">logi</l>
         <lc>logit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="num">ti</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="num">máŋga</l>
      </lg>
      <mg>
         <tg>
            <t pos="x">mange</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-nob/ShortSrc/shortDict_adj_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e>
      <lg>
         <l pos="a" context="olmmoš">spiehkasteaddji</l>
      </lg>
      <mg>
         <tg>
            <t pos="a">avvikende</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="a" context="olmmoš">triviála</l>
      </lg>
      <mg>
         <tg>
            <t pos="a">trivial</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="a" context="olmmoš">ulbmilaš</l>
      </lg>
      <mg>
         <tg>
            <t pos="a">strategisk</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-nob/src/negverb_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e usage="ped" src="nj">
      <lg>
         <l pos="v" context="mun">ii</l>
         <analysis>Verb_Prs_Sg3</analysis>
         <mini_paradigm>
            <analysis ms="Verb_Prs_Sg1">
               <wordform>in</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Sg2">
               <wordform>it</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Sg3">
               <wordform>ii</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Du1">
               <wordform>ean</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Du2">
               <wordform>eahppi</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Du3">
               <wordform>eaba</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Pl1">
               <wordform>eat</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Pl2">
               <wordform>ehpet</wordform>
            </analysis>
            <analysis ms="Verb_Prs_Pl3">
               <wordform>eai</wordform>
            </analysis>
         </mini_paradigm>
      </lg>
      <mg>
         <tg>
            <t pos="v">ikke</t>
         </tg>
      </mg>
   </e>

   <e>
      <lg>
         <l pos="pron_dublu_in">in</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Sg1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_it">it</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Sg2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_ii">ii</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Sg3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_ean">ean</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Du1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_eahppi">eahppi</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Du2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_eaba">eaba</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Du3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_eat">eat</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Pl1</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_ehpet">ehpet</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Pl2</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="pron_dublu_eai">eai</l>
         <lemma_ref>ii</lemma_ref>
         <analysis>Verb_Prs_Pl3</analysis>
      </lg>
      <mg>
         <tg>
            <t pos="pron">ikke</t>
         </tg>
      </mg>
   </e>
   
   
   
</r>
