=== giellalt/dict-sme-nob/src/smenob.dtd
<!ELEMENT r (e+) >
<!ELEMENT e (lgr mgr+)>
<!ELEMENT lg (l lc+)>
<!ELEMENT l (#PCDATA)>
<!ELEMENT lc (#PCDATA)>

<!ELEMENT mg (tg+)>
<!ELEMENT tg (t+ xg*)>

<!ELEMENT t (#PCDATA)>
<!ELEMENT xg ((x xt?)+)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT xt (#PCDATA)>

=== giellalt/dict-sme-nob/src/Interj_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smenob.dtd">
<r id="smenob" xml:lang="sme">
  <lics xml:space="preserve">
    <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
    <ref>Work by Nils Jernsletten, Giellatekno and Divvun at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
    <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
  </lics>
  <e>
    <lg freq="0">
      <l pos="Phrase">giittos eatnat</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <re>vanligvis som takk for maten</re>
        <t pos="Phrase">mange takk</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">buorre beaivi</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Phrase">god dag</t>
        <xg>
          <x>Buorre beaivi, rávkkai Ovllá. Ipmel atti, vástidii Elle.</x>
          <xt>God dag, hilste Ovllá. God dag, svarte Elle.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">buorre iđit</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Phrase">god morgen</t>
        <xg>
          <x>Buorre iđit, dajai Ánne go bođii kantuvrii. Ipmel atti, vástidii Biera.</x>
          <xt>God morgen, sa Ánne da hun kom til kontoret. God morgen, svarte Biera.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">buorre eahket</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Phrase">god kveld</t>
        <xg>
          <x>Buorre eahket, logai Risten kurssa oasseváldiide. Ipmel atti, vástidedje sii.</x>
          <xt>God kveld, sa Risten til kursdeltakerne. God kveld, svarte de.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">buorre idja</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Phrase">god natt</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">ipmel atti</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <re>som svar på hilsningene buorre iđit, buorre beaivi, buorre eahket</re>
        <t pos="Phrase">gud ga</t>
        <xg>
          <x>Buorre iđit, dajai Ánne go bođii kantuvrii. Ipmel atti, vástidii Biera.</x>
          <xt>God morgen, sa Ánne da hun kom til kontoret. God morgen, svarte Biera.</xt>
        </xg>
        <xg>
          <x>Buorre beaivi, rávkkai Ovllá. Ipmel atti, vástidii Elle.</x>
          <xt>God dag, hilste Ovllá. God dag, svarte Elle.</xt>
        </xg>
        <xg>
          <x>Buorre eahket, logai Risten kurssa oasseváldiide. Ipmel atti, vástidedje sii.</x>
          <xt>God kveld, sa Risten til kursdeltakerne. God kveld, svarte de.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="0">
      <l pos="Phrase">vuoi ihán</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">oi</t>
        <t pos="Phrase">å dæven</t>
        <xg>
          <x>Vuoi ihán, don leat čeahppi.</x>
          <xt>Oi, så flink du er.</xt>
        </xg>
        <xg>
          <x>Vuoi ihán, dáppe lea moivvas.</x>
          <xt>Å dæven, det er rotete her.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="159">
      <l pos="Interj">a-a</l>
      <algu lekseemi_id="82446" sanue_id="79503"/>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <re>uttrykk for at en nekter, avviser eller protesterer mot noe</re>
        <t pos="Interj">nei</t>
        <xg>
          <x>A-a, dan in háliit.</x>
          <xt>Nei, det vil jeg ikke.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="84">
      <l pos="Interj">bures</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <re>når man handhilser</re>
        <t pos="Phrase">god dag</t>
        <xg>
          <x>Bures!</x>
          <xt>God dag!</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Phrase">bures bures</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <re>når man handhilser, som svar</re>
        <t pos="Phrase">god dag</t>
        <xg>
          <x>Bures bures!</x>
          <xt>God dag!</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="239">
      <l pos="Interj">já</l>
      <algu lekseemi_id="31375" sanue_id="11588"/>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">jasså</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="32">
      <l pos="Interj">dearvva</l>
      <algu lekseemi_id="22720" sanue_id="47071"/>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">hei</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="459">
      <l pos="Interj">gea</l>
      <algu lekseemi_id="29855" sanue_id="66313"/>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="V">se</t>
        <xg>
          <x>Gea, beana skierbmu!</x>
          <xt>Se, hunden halter!</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg freq="2371">
      <l pos="Interj">vuoi</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">akk</t>
        <t pos="Interj">å</t>
        <xg>
          <x>Vuoi, go lea váivi.</x>
          <xt>Å akk, hvor trist det er.</xt>
        </xg>
        <xg>
          <x>Vuoi, man somá go soamis mus maid ballá.</x>
          <xt>Å, så artig at noen er redd for meg også.</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Interj">máistte</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">skål</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Interj">jugis</l>
    </lg>
    <mg>
      <tg xml:lang="nob">
        <t pos="Interj">skål</t>
      </tg>
    </mg>
  </e>
  <xhtml:script src="../../giella-core/dicts/scripts/gt_dictionary.js" type="text/javascript" xmlns:xhtml="http://www.w3.org/1999/xhtml"/>
</r>

=== giellalt/dict-sme-nob/src/N_Pl_smenob.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smenob.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smenob" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve"><lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic><ref>Work by Nils Jernsletten, Giellatekno and Divvun at UiT,
          and members of the language communities. Source code
          available at <a>https://github.com/giellalt/dict-sme-nob/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e src="fad">
      <lg freq="2">
         <l pos="N" nr="Pl">bellodatduorggat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">partipisk</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="0">
         <l pos="N" nr="Pl">dutkansearat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">forskningsinnsats</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="43">
         <l pos="N" nr="Pl">valáštallandoalut</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">idrettsarrangement</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="10">
         <l pos="N" nr="Pl">musihkkariemut</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">festspill</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="17">
         <l pos="N" nr="Pl">seaŋgagávnnit</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">sengetøy</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="5">
         <l pos="N" nr="Pl">konfirmašundoalut</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>konfirmasjonsselskap</re>
            <t pos="N">konfirmasjon</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="4">
         <l pos="N" nr="Pl">dutkkalmasat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">etterforskning</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="27">
         <l pos="N" nr="Pl">čoakkálmasat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>religiøst møte</re>
            <t pos="N">møte</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg freq="76">
         <l pos="N" nr="Pl">čoakkalmasat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>religiøst møte</re>
            <t pos="N">møte</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="46">
         <l pos="N" nr="Pl">čállinmearkkat</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">tegnsett</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="15">
         <l pos="N" nr="Pl">mátkkoštangolut</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="N">reiseutgift</t>
         </tg>
      </mg>
   </e>
   <e src="fad">
      <lg freq="60">
         <l pos="N" nr="Pl">jáffut</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>mel</re>
            <t pos="N">melsekk</t>
         </tg>
      </mg>
   </e>
   <xhtml:script xmlns:xhtml="http://www.w3.org/1999/xhtml" src="../../giella-core/dicts/scripts/gt_dictionary.js" type="text/javascript"/>
</r>

=== giellalt/dict-sme-nob/src/nounActor_smenob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD smenob//SE" "../scripts/smenob.dtd">
<r>
   <e src="nj">
      <lg>
         <l pos="n">bassi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">rengjøringsassistent</t>
            <t pos="m">vasker</t>
            <xg>
               <x>Skuvllas leat guokte bassi.</x>
               <xt>På skolen er det to rengjøringsassistenter.</xt>
            </xg>
            <xg>
               <x>Sii háliidit buoridit bargodili erenomážit bassiide.</x>
               <xt>De ønsker å forbedre arbeidsforholdene spesielt for rengjøringsassistentene.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">borri</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">spiser</t>
            <t pos="m">eter</t>
            <xg>
               <x>Dat olbmát ledje duhpatborrit, geaid lusa son bođii.</x>
               <xt>De karene var snustyggere, som han kom til.</xt>
            </xg>
             <xg>
               <x>Son háliidii báhčit goaskimiid, duoid boazoborriid.</x>
               <xt>Han/hun ville skyte ørnene, de reinspiserne.</xt>
            </xg>
        </tg>
      </mg>
      <mg>
         <tg>
            <t pos="n">uhyre</t>
            <xg>
               <x> </x>
               <xt></xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">dikšu</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">pleier</t>
            <xg>
               <x>Ođđa ossodahkii dárbbašuvvojit goitge logi dikšu.</x>
               <xt>Til den nye avdelingen trenges iallfall 10 pleiere.</xt>
            </xg>
            <xg>
               <x>Sii háliidit buoridit bargodili erenomážit dikšuide.</x>
               <xt>De ønsker å forbedre arbeidsforholdene spesielt for pleierne.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">goddi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">morder</t>
            <t pos="m">avliver</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">lávlu</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">sanger</t>
            <t pos="m">vokalist</t>
            <xg>
               <x>Oktiibuot logi juoigi ja guhtta lávlu leat lávddi alde beassášlávvordaga.</x>
               <xt>Tilsammen ti joikere og seks sangere er på scenen påskeaften.</xt>
            </xg>
            <xg>
               <x>Mii ozaimet doarjaga doallat kurssa juigiide ja lávluide.</x>
               <xt>Vi søkte om penger for at holde kurs for joikere og sangere.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">lohkki</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">leser</t>
            <xg>
               <x>Jurddašin jearahallat vihtta lohkki luopmoplánaid birra.</x>
               <xt>Jeg tenkte å intervje fem lesere om ferieplaner.</xt>
            </xg>
            <xg>
               <x>Áviisa sávvá buot lohkkiide ráfálaš ja buriid juovllaid.</x>
               <xt>Avisa ønsker fredelig og god jul til alle leserne.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">vuovdi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">selger</t>
            <xg>
               <x>Máŋga vuovdi ledje boahtán márkanii.</x>
               <xt>Mange selgere var kommet til markedet.</xt>
            </xg>
             <xg>
               <x>Mun dopmen máksit iežan velggiid buot vuovdiide.</x>
               <xt>Jeg skyndte meg å betale gjelda mi til alle selgerne.</xt>
            </xg>
        </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">jođiheaddji</l>
         <lc>-headdjit, -heddjiid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">leder</t>
            <t pos="m">styrer</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">prošeaktajođiheaddji</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">prosjektleder</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">sátnejođiheaddji</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">ordfører</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">bargi</l>
         <lc>bargit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">arbeider</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="m">arbeidstaker</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">dearvvašvuođabargi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">helsearbeider</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">fabrihkkabargi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">fabrikkarbeider</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">gávpebargi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">ekspeditør</t>
            <t pos="m">butikkansatt</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">kántorbargi</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">kontorarbeider</t>
            <t pos="m">kontoransatt</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">ássi</l>
         <lc>ássit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">innbygger</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">girječálli</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">forfatter</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">čálli</l>
         <lc>čállit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">forfatter</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="m">sekretær</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="m">skribent</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">čuoigi</l>
         <lc>čuoigit</lc>
         <lc>čuigiid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">skiløper</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">dutki</l>
         <lc>dutkit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">forsker</t>
         </tg>
      </mg>
   </e>
   <e usage="ped">
      <lg>
         <l pos="n">biebmoealli</l>
      </lg>
      <mg>
         <tg>
            <t pos="n">kjæledyr</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">ealli</l>
         <lc>eallit</lc>
         <lc>elliid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="n">levende vesen</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="n">dyr</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">girdi</l>
         <lc>girdit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="n">fly</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="x">flyver</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">guođoheaddji</l>
         <lc>-headdjit</lc>
         <lc>-heddjiid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">gjeter</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">jábmi</l>
         <lc>jábmit</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">død</t>
            <t pos="n">lik</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">máhttájeaddji</l>
         <lc>-jeaddjit</lc>
         <lc>-jeddjiid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">disippel</t>
            <t pos="m">apostel</t>
         </tg>
      </mg>
   </e>
   <e usage="ped" src="nj">
      <lg>
         <l pos="n">oahpaheaddji</l>
         <lc>-headdjit</lc>
         <lc>-heddjiid</lc>
      </lg>
      <mg>
         <tg>
            <t pos="m">lærer</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">vearredahkki</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">forbryter</t>
         </tg>
      </mg>
   </e>
   <e src="nj">
      <lg>
         <l pos="n">njoammu</l>
      </lg>
      <mg>
         <tg>
            <t pos="m">smittsom sykdom</t>
         </tg>
      </mg>
   </e>
</r>
